# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		El blog de Noé Domínguez
tagline:	'blog'
description:	'Mi blog personal sobre tecnología & programación'
url:		http://poguez.github.io
commentsystem:	disqus
disqus:		poguez

author:
  name:		'Noé Domínguez Porras'
url:		https://mx.linkedin.com/in/noedominguez/

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/noe_dgz
    desc:	Sígueme en Twitter

  - icon:	github
    url:	https://github.com/poguez
    desc:	Sigue mis proyectos en Github

  - icon:	googleplus-alt
    url:	https://google.com/+NoeDominguez
    desc:	Agrégame en google+

  - icon:	feed
    url:	http://poguez.github.io/atom.xml
    desc:	Suscríbete a mi feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	Sobre mi
    url:	/sobre-mi
    
copyright:
  author:	Noé Domínguez
  url:		http://poguez.github.io
  type_title:	Algunos derechos reservados
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-41550586-1
