# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		El blog de Noé Domínguez
tagline:	'blog'
description:	'Mi blog personal, tecnología & programación'
commentsystem:	disqus
disqus:		poguez
fb_app_id: 181345208885623

author:
  name:		'Noé Domínguez Porras'

url: https://noedominguez.com

paginate:	20

languages: ["en", "es"]
default_lang: "en"

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover_cafe.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/noe_dgz
    desc:	Sígueme en Twitter

  - icon:	github
    url:	https://github.com/poguez
    desc:	Sigue mis proyectos en Github

  - icon:	feed
    url:	http://poguez.github.io/atom.xml
    desc:	Suscríbete a mi feed

menu:
  - title:	Home
    url:	/

  - title:	Sobre mi
    url:	/sobre-mi

copyright:
  author:	Noé Domínguez
  url:		http://poguez.github.io
  type_title:	Algunos derechos reservados
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# don’t localize assets/static files
exclude_from_localizations:
  - assets
  - images
  - css
  - js
  - favicon.ico
  - CNAME
  -
# Assets & Styles

sass:
  sass_dir: /assets/css
#  style: compressed

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-41550586-1

# Jekyll Gems
gems: [jekyll-paginate, bourbon]
# Plugins
plugins: [ jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed, jekyll-polyglot]
