# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		El blog de Noé Domínguez
tagline:	'blog'
description:	'Mi blog personal, tecnología & programación'
commentsystem:	disqus
disqus:		poguez
fb_app_id: 181345208885623

author:
  name:		'Noé Domínguez Porras'
url: https://poguez.github.io

paginate:	10

languages:
  - name:	'Spanish'
    code:	es
    url:	'/es'
    permalink:	'/es/blog/:title'

  - name:	'English'
    code:	en
    url:	'/en'
    permalink:	'/en/blog/:title'

default_lang: es

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover_cafe.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/noe_dgz
    desc:	Sígueme en Twitter

  - icon:	github
    url:	https://github.com/poguez
    desc:	Sigue mis proyectos en Github

  - icon:	googleplus-alt
    url:	https://google.com/+NoeDominguez
    desc:	Agrégame en google+

  - icon:	feed
    url:	http://poguez.github.io/atom.xml
    desc:	Suscríbete a mi feed

menu:
  - title:	Home
    url:	/

  - title:	Sobre mi
    url:	/sobre-mi

copyright:
  author:	Noé Domínguez
  url:		http://poguez.github.io
  type_title:	Algunos derechos reservados
  type_url:	http://creativecommons.org/licenses/by-nc/2.5


# Assets & Styles

sass:
  sass_dir: /assets/css
#  style: compressed

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics: UA-41550586-1

# Jekyll Gems
gems: [jekyll-paginate, bourbon]
# Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed]

